name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: ashik1234/toaseen-cap-cms
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ashik1234
          password: k42!45h!k
